// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {nodeservice} from '../models';
import {main} from '../models';

export function AIChat(arg1:string,arg2:string):Promise<Record<string, any>>;

export function AIDetectGPU():Promise<Record<string, any>>;

export function AIHealth():Promise<Record<string, any>>;

export function AIListTools():Promise<Array<string>>;

export function AIStart():Promise<Record<string, any>>;

export function AIStop():Promise<Record<string, any>>;

export function AIToolExecute(arg1:string):Promise<Record<string, any>>;

export function BackupWallet(arg1:string):Promise<Record<string, any>>;

export function BenchmarkMiner(arg1:number,arg2:number):Promise<Record<string, any>>;

export function ChangeWalletPassphrase(arg1:string,arg2:string):Promise<Record<string, any>>;

export function CheckStorage():Promise<Record<string, any>>;

export function CoinInfo():Promise<Record<string, any>>;

export function CreateWallet(arg1:string):Promise<Record<string, any>>;

export function DisconnectNode(arg1:string):Promise<Record<string, any>>;

export function Doctor():Promise<Record<string, any>>;

export function EnableAddressAndTxIndexConfig():Promise<Record<string, any>>;

export function EncryptWallet(arg1:string):Promise<Record<string, any>>;

export function ForcePeerSync():Promise<Record<string, any>>;

export function ForceStopMiner():Promise<Record<string, any>>;

export function GetBalance():Promise<Record<string, any>>;

export function GetBlockByHash(arg1:string):Promise<Record<string, any>>;

export function GetBlockByHeight(arg1:number):Promise<Record<string, any>>;

export function GetBlockchainInfo():Promise<Record<string, any>>;

export function GetChainTiming():Promise<Record<string, any>>;

export function GetDefaultAddress():Promise<string>;

export function GetExplorerSummary():Promise<Record<string, any>>;

export function GetLaunchpadAPI(arg1:string):Promise<Record<string, any>>;

export function GetMempool():Promise<Record<string, any>>;

export function GetMinerStatus():Promise<Record<string, any>>;

export function GetNewAddress():Promise<string>;

export function GetNodeConfig():Promise<Record<string, any>>;

export function GetPeerInfo():Promise<Array<any>>;

export function GetRecentBlocks(arg1:number):Promise<Array<Record<string, any>>>;

export function GetSupplyInfo():Promise<Record<string, any>>;

export function GetSyncStatus():Promise<Record<string, any>>;

export function GetTransaction(arg1:string):Promise<Record<string, any>>;

export function GetTransactionStatus(arg1:string):Promise<Record<string, any>>;

export function GetWalletSummary():Promise<Record<string, any>>;

export function GetWalletTransaction(arg1:string):Promise<Record<string, any>>;

export function ImportWallet(arg1:string,arg2:string):Promise<Record<string, any>>;

export function ListPendingTransactions():Promise<Array<Record<string, any>>>;

export function ListReceiveAddresses():Promise<Array<string>>;

export function ListWalletTransactions():Promise<Array<Record<string, any>>>;

export function LockWallet():Promise<Record<string, any>>;

export function NodeStatus():Promise<nodeservice.Status>;

export function OpenConfigDir():Promise<Record<string, any>>;

export function OpenConfigFile():Promise<Record<string, any>>;

export function OpenDataDir():Promise<Record<string, any>>;

export function OpenLifecycleLog():Promise<Record<string, any>>;

export function Quit():Promise<void>;

export function RebroadcastTransaction(arg1:string):Promise<Record<string, any>>;

export function ReconnectPeers():Promise<Record<string, any>>;

export function RemoveLocalPendingTransaction(arg1:string):Promise<Record<string, any>>;

export function RestartInternalNode():Promise<Record<string, any>>;

export function RestoreWalletBackup(arg1:string):Promise<Record<string, any>>;

export function RunRPCCommand(arg1:string):Promise<Record<string, any>>;

export function SaveNetworkSettings(arg1:main.NetworkSettings):Promise<main.NetworkSettings>;

export function SaveSettings(arg1:main.Settings):Promise<main.Settings>;

export function SearchExplorer(arg1:string):Promise<Record<string, any>>;

export function SendToAddress(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function SendTokenBurn(arg1:Record<string, any>,arg2:string):Promise<Record<string, any>>;

export function SendTokenDeploy(arg1:Record<string, any>,arg2:string):Promise<Record<string, any>>;

export function SendTokenTransfer(arg1:Record<string, any>,arg2:string):Promise<Record<string, any>>;

export function SetDefaultMiningAddress(arg1:string):Promise<Record<string, any>>;

export function SetMinerThreads(arg1:number):Promise<Record<string, any>>;

export function Snapshot():Promise<Record<string, any>>;

export function SplitCoins(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Record<string, any>>;

export function StartMiner(arg1:number):Promise<Record<string, any>>;

export function StartNode():Promise<void>;

export function StopMiner():Promise<Record<string, any>>;

export function StopNode():Promise<Record<string, any>>;

export function TestConfiguredNodes():Promise<Array<main.NodeTestResult>>;

export function TestNodeConnection(arg1:string):Promise<main.NodeTestResult>;

export function UnlockWallet(arg1:string,arg2:number):Promise<Record<string, any>>;

export function WalletExists():Promise<boolean>;

export function WindowMinimise():Promise<void>;

export function WindowToggleMaximise():Promise<void>;
