// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AIChat(arg1, arg2) {
  return window['go']['main']['App']['AIChat'](arg1, arg2);
}

export function AIConfigure(arg1, arg2, arg3) {
  return window['go']['main']['App']['AIConfigure'](arg1, arg2, arg3);
}

export function AIDetectGPU() {
  return window['go']['main']['App']['AIDetectGPU']();
}

export function AIHealth() {
  return window['go']['main']['App']['AIHealth']();
}

export function AIImageGenerate(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AIImageGenerate'](arg1, arg2, arg3, arg4);
}

export function AIListTools() {
  return window['go']['main']['App']['AIListTools']();
}

export function AIModels() {
  return window['go']['main']['App']['AIModels']();
}

export function AIResearch(arg1) {
  return window['go']['main']['App']['AIResearch'](arg1);
}

export function AIStart() {
  return window['go']['main']['App']['AIStart']();
}

export function AIStop() {
  return window['go']['main']['App']['AIStop']();
}

export function AIToolExecute(arg1) {
  return window['go']['main']['App']['AIToolExecute'](arg1);
}

export function BackupWallet(arg1) {
  return window['go']['main']['App']['BackupWallet'](arg1);
}

export function BenchmarkMiner(arg1, arg2) {
  return window['go']['main']['App']['BenchmarkMiner'](arg1, arg2);
}

export function ChangeWalletPassphrase(arg1, arg2) {
  return window['go']['main']['App']['ChangeWalletPassphrase'](arg1, arg2);
}

export function CheckStorage() {
  return window['go']['main']['App']['CheckStorage']();
}

export function CoinInfo() {
  return window['go']['main']['App']['CoinInfo']();
}

export function CreateWallet(arg1) {
  return window['go']['main']['App']['CreateWallet'](arg1);
}

export function DisconnectNode(arg1) {
  return window['go']['main']['App']['DisconnectNode'](arg1);
}

export function Doctor() {
  return window['go']['main']['App']['Doctor']();
}

export function EnableAddressAndTxIndexConfig() {
  return window['go']['main']['App']['EnableAddressAndTxIndexConfig']();
}

export function EncryptWallet(arg1) {
  return window['go']['main']['App']['EncryptWallet'](arg1);
}

export function ForcePeerSync() {
  return window['go']['main']['App']['ForcePeerSync']();
}

export function ForceStopMiner() {
  return window['go']['main']['App']['ForceStopMiner']();
}

export function GetBalance() {
  return window['go']['main']['App']['GetBalance']();
}

export function GetBlockByHash(arg1) {
  return window['go']['main']['App']['GetBlockByHash'](arg1);
}

export function GetBlockByHeight(arg1) {
  return window['go']['main']['App']['GetBlockByHeight'](arg1);
}

export function GetBlockchainInfo() {
  return window['go']['main']['App']['GetBlockchainInfo']();
}

export function GetChainTiming() {
  return window['go']['main']['App']['GetChainTiming']();
}

export function GetDefaultAddress() {
  return window['go']['main']['App']['GetDefaultAddress']();
}

export function GetExplorerSummary() {
  return window['go']['main']['App']['GetExplorerSummary']();
}

export function GetLaunchpadAPI(arg1) {
  return window['go']['main']['App']['GetLaunchpadAPI'](arg1);
}

export function GetMempool() {
  return window['go']['main']['App']['GetMempool']();
}

export function GetMinerStatus() {
  return window['go']['main']['App']['GetMinerStatus']();
}

export function GetNewAddress() {
  return window['go']['main']['App']['GetNewAddress']();
}

export function GetNodeConfig() {
  return window['go']['main']['App']['GetNodeConfig']();
}

export function GetPeerInfo() {
  return window['go']['main']['App']['GetPeerInfo']();
}

export function GetRecentBlocks(arg1) {
  return window['go']['main']['App']['GetRecentBlocks'](arg1);
}

export function GetSupplyInfo() {
  return window['go']['main']['App']['GetSupplyInfo']();
}

export function GetSyncStatus() {
  return window['go']['main']['App']['GetSyncStatus']();
}

export function GetTransaction(arg1) {
  return window['go']['main']['App']['GetTransaction'](arg1);
}

export function GetTransactionStatus(arg1) {
  return window['go']['main']['App']['GetTransactionStatus'](arg1);
}

export function GetWalletSummary() {
  return window['go']['main']['App']['GetWalletSummary']();
}

export function GetWalletTransaction(arg1) {
  return window['go']['main']['App']['GetWalletTransaction'](arg1);
}

export function ImportWallet(arg1, arg2) {
  return window['go']['main']['App']['ImportWallet'](arg1, arg2);
}

export function ListPendingTransactions() {
  return window['go']['main']['App']['ListPendingTransactions']();
}

export function ListReceiveAddresses() {
  return window['go']['main']['App']['ListReceiveAddresses']();
}

export function ListWalletTransactions() {
  return window['go']['main']['App']['ListWalletTransactions']();
}

export function LockWallet() {
  return window['go']['main']['App']['LockWallet']();
}

export function NodeStatus() {
  return window['go']['main']['App']['NodeStatus']();
}

export function OpenConfigDir() {
  return window['go']['main']['App']['OpenConfigDir']();
}

export function OpenConfigFile() {
  return window['go']['main']['App']['OpenConfigFile']();
}

export function OpenDataDir() {
  return window['go']['main']['App']['OpenDataDir']();
}

export function OpenLifecycleLog() {
  return window['go']['main']['App']['OpenLifecycleLog']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function RebroadcastTransaction(arg1) {
  return window['go']['main']['App']['RebroadcastTransaction'](arg1);
}

export function ReconnectPeers() {
  return window['go']['main']['App']['ReconnectPeers']();
}

export function RemoveLocalPendingTransaction(arg1) {
  return window['go']['main']['App']['RemoveLocalPendingTransaction'](arg1);
}

export function RestartInternalNode() {
  return window['go']['main']['App']['RestartInternalNode']();
}

export function RestoreWalletBackup(arg1) {
  return window['go']['main']['App']['RestoreWalletBackup'](arg1);
}

export function RunRPCCommand(arg1) {
  return window['go']['main']['App']['RunRPCCommand'](arg1);
}

export function SaveNetworkSettings(arg1) {
  return window['go']['main']['App']['SaveNetworkSettings'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SearchExplorer(arg1) {
  return window['go']['main']['App']['SearchExplorer'](arg1);
}

export function SendToAddress(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendToAddress'](arg1, arg2, arg3);
}

export function SendTokenBurn(arg1, arg2) {
  return window['go']['main']['App']['SendTokenBurn'](arg1, arg2);
}

export function SendTokenDeploy(arg1, arg2) {
  return window['go']['main']['App']['SendTokenDeploy'](arg1, arg2);
}

export function SendTokenTransfer(arg1, arg2) {
  return window['go']['main']['App']['SendTokenTransfer'](arg1, arg2);
}

export function SetDefaultMiningAddress(arg1) {
  return window['go']['main']['App']['SetDefaultMiningAddress'](arg1);
}

export function SetMinerThreads(arg1) {
  return window['go']['main']['App']['SetMinerThreads'](arg1);
}

export function Snapshot() {
  return window['go']['main']['App']['Snapshot']();
}

export function SplitCoins(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SplitCoins'](arg1, arg2, arg3, arg4);
}

export function StartMiner(arg1) {
  return window['go']['main']['App']['StartMiner'](arg1);
}

export function StartNode() {
  return window['go']['main']['App']['StartNode']();
}

export function StopMiner() {
  return window['go']['main']['App']['StopMiner']();
}

export function StopNode() {
  return window['go']['main']['App']['StopNode']();
}

export function TestConfiguredNodes() {
  return window['go']['main']['App']['TestConfiguredNodes']();
}

export function TestNodeConnection(arg1) {
  return window['go']['main']['App']['TestNodeConnection'](arg1);
}

export function UnlockWallet(arg1, arg2) {
  return window['go']['main']['App']['UnlockWallet'](arg1, arg2);
}

export function WalletExists() {
  return window['go']['main']['App']['WalletExists']();
}

export function WindowMinimise() {
  return window['go']['main']['App']['WindowMinimise']();
}

export function WindowToggleMaximise() {
  return window['go']['main']['App']['WindowToggleMaximise']();
}
