name: Docker

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions: read-all

jobs:
  publish:
    name: Build and publish Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db # v3.11.0

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@0d18d215baa5ad9cb141f0c13d832016b39f5dcc # v3.5.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@f7b4ed12385588c3e0a0d1e87e07c64b0b64d615 # v5.6.0
        with:
          images: ghcr.io/${{ github.repository }}
          tags: type=semver,pattern={{version}}

      - name: Build and push
        uses: docker/build-push-action@dcc3d0a2cc9e558a6f3fc1ae7af72f5c9d15b237 # v6.16.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max